### ISSUE TITLE
FEATURE: Create map component for Contact Us page

### ISSUE THREAD

**Issue by EshaanAgg** [COPS-IITBHU/sdg-site#133]
Design:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/96648934/206867231-6cbc7329-6a8e-4c18-884d-73ced2e686ed.png">

**Comment by shriya-tiwari** [comment]
@IamEzio please assgn this to me.

**Comment by DevilzzNikhil** [comment]
@IamEzio  Want to work upon
