### ISSUE TITLE
Failing GitHub Actions

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/sdg-site#19]
I can see the last three workflow runs failed in the "Build Project" step with an error related to threads. This step runs the `generate` command as written in the `package.json`.

## Expected Behavior
Since there's nothing wrong as far as I can see in the code for this repo, things are expected to work fine.

## Current Behavior
Builds are failing.

## Possible Reason
The GitHub actions seem to run with Node with versions 14 and 16 from the following lines in the workflow.

https://github.com/COPS-IITBHU/sdg-site/blob/4492dae66411880ab144ddb0a309e6351c0982cd/.github/workflows/ci.yml#L15-L18

The errors in the actions seem to be related to the [node-fibers](https://github.com/laverdet/node-fibers) package in the `package.json`. As per the package [repo](https://github.com/laverdet/node-fibers#readme), the package is obsolete on newer versions of Node.js due to a breaking change in the V8 engine and has reached its EOL.

Read below:

> Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial.

IMO, the builds are failing when the node v16 is being used.

## Possible Solution

There are two possible solutions to this:

1. Remove the `fibers` package from `package.json` if it isn't being used anywhere.
2. Use a version of node strictly lower than 16.

**Comment by king-11** [comment]
Thanks for flagging at @shubhanshu02 this was fixed in the recent commit that I made `fibers` was needed for a 2x compilation of SASS maybe we can look at it later not necessary now.

**Comment by king-11** [comment]
Closed by #8a032be
