### ISSUE TITLE
Final Touchup

### ISSUE THREAD

**Issue by king-11** [COPS-IITBHU/sdg-site#45]
Following is the final worklist to get the site ready for the public reveal

- [x] Image Webp
- [x] Image sizes and lazy loading
- [x] accessible tags
- [x] previewer additon
- [x] project update
- [x] dns change
- [x] alums addition
- [x] members check
- [x] carousel errors fix
- [x] carousel text overflow
- [x] Meta tags
- [x] Image Selection at different places

**Comment by king-11** [comment]
@aswinidev the carousel throws an error for `bias` undefined at times when calling `toLowerCase`

**Comment by king-11** [comment]
@puranjayK add in previewer to the JSON file in the content folder whenever you are ready.

**Comment by IamEzio** [comment]
Some more changes to be done - 
- [ ] Telegram bot image to be added in the projects section
- [ ] Update font classes 
- [ ] Contact us page headings should be made responsive

**Comment by king-11** [comment]
- [ ] Footer Blur

**Comment by king-11** [comment]
- [ ] Use Nuxt Link for internal links

**Comment by king-11** [comment]
Site is Ready now 💥💥💥
