### ISSUE TITLE
Enhancement: Contact Us Page Map

### ISSUE THREAD

**Issue by EshaanAgg** [COPS-IITBHU/sdg-site#98]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/96648934/193418586-009b28df-3e9b-4988-b1e2-a63966d2acbe.png">

Should add some sort of background to the `Contact Us` text on the map so that there is better contrast and for better readability of the title.

**Comment by IamEzio** [comment]
Go ahead @EshaanAgg.
